### ISSUE TITLE
host allocation of size 209715200 failed [test_pretrained.py]

### ISSUE THREAD

**Issue by ghost** [ctensmeyer/pagenet#1]
@ctensmeyer @herobd Thank you for your hard work.

I ran `test_pretrained.py` and it failed. Below is the image which I tested on:

![1](https://user-images.githubusercontent.com/33478216/45714765-3fd44100-bb9b-11e8-8a86-8d1b9b84d51e.jpg)

The command used to test, note that I use `-3` so that it only uses CPU:
```
(python22) home@home-lnx:~/pagenet$ python2 test_pretrained.py --gpu -3 ./input/ ./input/manifest.txt cbad ./out/out
```

The produced error:
```
Processed 0/1 Images
F0918 23:18:45.175485  8978 syncedmem.hpp:33] Check failed: *ptr host allocation of size 209715200 failed
*** Check failure stack trace: ***
Aborted (core dumped)
```

And attaching the complete error log:
[pgneterro.txt](https://github.com/ctensmeyer/pagenet/files/2394415/pgneterro.txt)

**Comment by ctensmeyer** [comment]
That error is a failure to allocate enough memory on the CPU side RAM.  I suggest you terminate other processes that are consuming memory on your system and try again.

**Comment by ghost** [comment]
@ctensmeyer I have 3GB free ram, and my 4 cpu's are mostly not used, & my test image size is only 110 kb.
What should I do?

**Comment by ctensmeyer** [comment]
The test image size doesn't matter as all images are resized to 256x256.
3GB ought to be enough RAM, so I don't know what the problem would be in
the memory allocation.

**Comment by ghost** [comment]
@ctensmeyer can you tell me the precise versions of pagenet dependencies? python x.x openCV x.x  .....
if you are using conda, then:
```
source activate your_environment_name
conda env export > environment.yml
```
and send the environment.yml file here.

**Comment by ghost** [comment]
Also, can pagenet recognize multiple pages at once?
can pagenet be used to extract text-lines?

**Comment by ctensmeyer** [comment]
Python 2.7, OpenCV 3.2, any recent numpy.  The repo says matplotlib, but I
don't see it used anywhere in the code.

Pagenet doesn't do text lines, but it can segment multiple pages.  E.g. if
you have both pages of an open book in the image, it will predict the
region around both pages.
